### ISSUE TITLE
Reduce batch executor boilerplate

### ISSUE THREAD

**Issue by dapplion** [gnosischain/reth_gnosis#23]
Upstream Reth merged a composable Block executor
- https://github.com/paradigmxyz/reth/issues/11274

We can drop a few hundred lines of boilerplate following a similar refactor to
- https://github.com/paradigmxyz/reth/pull/11846

**Comment by SkandaBhat** [comment]
I can pick this up!

**Comment by debjit-bw** [comment]
Hey @SkandaBhat, while you're at it, would be great if you could update the reth* dependencies to commit `e93e373853ae2735fc6ca86ef0273bcacfd15c31` or later. Ref: [e93e37](https://github.com/paradigmxyz/reth/tree/e93e373853ae2735fc6ca86ef0273bcacfd15c31)

**Comment by SkandaBhat** [comment]
there's a bit of refactor to be done to support `e93e373853ae2735fc6ca86ef0273bcacfd15c31`, will open a draft soon this week including the block executor refactor

**Comment by debjit-bw** [comment]
Hey @SkandaBhat, any progress?

**Comment by SkandaBhat** [comment]
ill have a draft in a day or two @debjit-bw
